apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-lab
  labels:
    app: ubuntu-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-lab
  template:
    metadata:
      labels:
        app: ubuntu-lab
    spec:
      containers:
        - name: ubuntu
          image: "ubuntu:22.04"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt update && apt install -y postgresql-client && \
              chmod +x /workspace/scripts/create_user.sh && \
              /workspace/scripts/create_user.sh && \
              tail -f /dev/null
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          volumeMounts:
            - name: volume-data
              mountPath: /workspace
      volumes:
        - name: volume-data
          hostPath:
            path: /home/oliveira/postgres_pgadmin/postgre_project/volume_data
