apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: postgres
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
